[mypy]
python_version = 3.11
show_error_codes = true
disable_error_code = import-untyped
follow_imports = skip

[mypy-homeassistant.*]
ignore_missing_imports = True

[mypy-voluptuous.*]
ignore_missing_imports = True

[mypy-telnetlib]
ignore_missing_imports = True

[mypy-tripp_lite_srcool.config_flow]
# ConfigFlow registers domain via __init_subclass__ keyword argument.
disable_error_code = call-arg
